#!/usr/bin/env osascript -l JavaScript

var app = Application.currentApplication();

app.includeStandardAdditions = true

app.displayNotification('hello, world!', {withTitle: 'Notification title', subtitle: 'Notification subtitle'});
